//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchHKPMIPatientByCaseNoResponse", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class SearchHKPMIPatientByCaseNoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ns2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.PatientDemoEnquiryResult PatientDemoEnquiryResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ns2 {
            get {
                return this.Ns2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ns2Field, value) != true)) {
                    this.Ns2Field = value;
                    this.RaisePropertyChanged("Ns2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.PatientDemoEnquiryResult PatientDemoEnquiryResult {
            get {
                return this.PatientDemoEnquiryResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientDemoEnquiryResultField, value) != true)) {
                    this.PatientDemoEnquiryResultField = value;
                    this.RaisePropertyChanged("PatientDemoEnquiryResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDemoEnquiryResult", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class PatientDemoEnquiryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.CaseList CaseListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Patient PatientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.CaseList CaseList {
            get {
                return this.CaseListField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseListField, value) != true)) {
                    this.CaseListField = value;
                    this.RaisePropertyChanged("CaseList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseList", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class CaseList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Case CaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Case Case {
            get {
                return this.CaseField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseField, value) != true)) {
                    this.CaseField = value;
                    this.RaisePropertyChanged("Case");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChineseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidentialFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExactDOBFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HKIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HkicSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastPayCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCCode1 {
            get {
                return this.CCCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CCCode1Field, value) != true)) {
                    this.CCCode1Field = value;
                    this.RaisePropertyChanged("CCCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCCode2 {
            get {
                return this.CCCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CCCode2Field, value) != true)) {
                    this.CCCode2Field = value;
                    this.RaisePropertyChanged("CCCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCCode3 {
            get {
                return this.CCCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CCCode3Field, value) != true)) {
                    this.CCCode3Field = value;
                    this.RaisePropertyChanged("CCCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChineseName {
            get {
                return this.ChineseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChineseNameField, value) != true)) {
                    this.ChineseNameField = value;
                    this.RaisePropertyChanged("ChineseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfidentialFlag {
            get {
                return this.ConfidentialFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidentialFlagField, value) != true)) {
                    this.ConfidentialFlagField = value;
                    this.RaisePropertyChanged("ConfidentialFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactDOBFlag {
            get {
                return this.ExactDOBFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.ExactDOBFlagField, value) != true)) {
                    this.ExactDOBFlagField = value;
                    this.RaisePropertyChanged("ExactDOBFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HKID {
            get {
                return this.HKIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HKIDField, value) != true)) {
                    this.HKIDField = value;
                    this.RaisePropertyChanged("HKID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HkicSymbol {
            get {
                return this.HkicSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.HkicSymbolField, value) != true)) {
                    this.HkicSymbolField = value;
                    this.RaisePropertyChanged("HkicSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPayCode {
            get {
                return this.LastPayCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastPayCodeField, value) != true)) {
                    this.LastPayCodeField = value;
                    this.RaisePropertyChanged("LastPayCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePhone {
            get {
                return this.OfficePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficePhoneField, value) != true)) {
                    this.OfficePhoneField = value;
                    this.RaisePropertyChanged("OfficePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Case", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class Case : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospitalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WardClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WardCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionDatetime {
            get {
                return this.AdmissionDatetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionDatetimeField, value) != true)) {
                    this.AdmissionDatetimeField = value;
                    this.RaisePropertyChanged("AdmissionDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BedNo {
            get {
                return this.BedNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BedNoField, value) != true)) {
                    this.BedNoField = value;
                    this.RaisePropertyChanged("BedNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HospitalCode {
            get {
                return this.HospitalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalCodeField, value) != true)) {
                    this.HospitalCodeField = value;
                    this.RaisePropertyChanged("HospitalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientType {
            get {
                return this.PatientTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientTypeField, value) != true)) {
                    this.PatientTypeField = value;
                    this.RaisePropertyChanged("PatientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceCode {
            get {
                return this.SourceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceCodeField, value) != true)) {
                    this.SourceCodeField = value;
                    this.RaisePropertyChanged("SourceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceIndicator {
            get {
                return this.SourceIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIndicatorField, value) != true)) {
                    this.SourceIndicatorField = value;
                    this.RaisePropertyChanged("SourceIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialty {
            get {
                return this.SpecialtyField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialtyField, value) != true)) {
                    this.SpecialtyField = value;
                    this.RaisePropertyChanged("Specialty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WardClass {
            get {
                return this.WardClassField;
            }
            set {
                if ((object.ReferenceEquals(this.WardClassField, value) != true)) {
                    this.WardClassField = value;
                    this.RaisePropertyChanged("WardClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WardCode {
            get {
                return this.WardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WardCodeField, value) != true)) {
                    this.WardCodeField = value;
                    this.RaisePropertyChanged("WardCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullEnglishAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Record_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictCode {
            get {
                return this.DistrictCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictCodeField, value) != true)) {
                    this.DistrictCodeField = value;
                    this.RaisePropertyChanged("DistrictCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullEnglishAddress {
            get {
                return this.FullEnglishAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullEnglishAddressField, value) != true)) {
                    this.FullEnglishAddressField = value;
                    this.RaisePropertyChanged("FullEnglishAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Record_id {
            get {
                return this.Record_idField;
            }
            set {
                if ((object.ReferenceEquals(this.Record_idField, value) != true)) {
                    this.Record_idField = value;
                    this.RaisePropertyChanged("Record_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientSoapServiceReference.IPatientSoapService")]
    public interface IPatientSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientSoapService/searchHKPMIPatientByCaseNo", ReplyAction="http://tempuri.org/IPatientSoapService/searchHKPMIPatientByCaseNoResponse")]
        Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.SearchHKPMIPatientByCaseNoResponse searchHKPMIPatientByCaseNo(string hospitalCode, string caseNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPatientSoapServiceChannel : Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.IPatientSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientSoapServiceClient : System.ServiceModel.ClientBase<Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.IPatientSoapService>, Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.IPatientSoapService {
        
        public PatientSoapServiceClient() {
        }
        
        public PatientSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Demo.HL7MessageParser.ServiceSimulator.Test.PatientSoapServiceReference.SearchHKPMIPatientByCaseNoResponse searchHKPMIPatientByCaseNo(string hospitalCode, string caseNo) {
            return base.Channel.searchHKPMIPatientByCaseNo(hospitalCode, caseNo);
        }
    }
}
