//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicationProfile", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class MedicationProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MedProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedProfileMoItem[] MedProfileMoItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNum {
            get {
                return this.CaseNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumField, value) != true)) {
                    this.CaseNumField = value;
                    this.RaisePropertyChanged("CaseNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MedProfileId {
            get {
                return this.MedProfileIdField;
            }
            set {
                if ((this.MedProfileIdField.Equals(value) != true)) {
                    this.MedProfileIdField = value;
                    this.RaisePropertyChanged("MedProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedProfileMoItem[] MedProfileMoItems {
            get {
                return this.MedProfileMoItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MedProfileMoItemsField, value) != true)) {
                    this.MedProfileMoItemsField = value;
                    this.RaisePropertyChanged("MedProfileMoItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedProfileMoItem", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class MedProfileMoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MedProfileMoItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedProfilePoItem[] MedProfilePoItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MedProfileMoItemId {
            get {
                return this.MedProfileMoItemIdField;
            }
            set {
                if ((this.MedProfileMoItemIdField.Equals(value) != true)) {
                    this.MedProfileMoItemIdField = value;
                    this.RaisePropertyChanged("MedProfileMoItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedProfilePoItem[] MedProfilePoItems {
            get {
                return this.MedProfilePoItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MedProfilePoItemsField, value) != true)) {
                    this.MedProfilePoItemsField = value;
                    this.RaisePropertyChanged("MedProfilePoItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedProfilePoItem", Namespace="http://schemas.datacontract.org/2004/07/Demo.HL7MessageParser.Models")]
    [System.SerializableAttribute()]
    public partial class MedProfilePoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MedProfilePoItemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MedProfilePoItemId {
            get {
                return this.MedProfilePoItemIdField;
            }
            set {
                if ((this.MedProfilePoItemIdField.Equals(value) != true)) {
                    this.MedProfilePoItemIdField = value;
                    this.RaisePropertyChanged("MedProfilePoItemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MedicationProfileRESTServiceReference.IMedicationProfileRESTService")]
    public interface IMedicationProfileRESTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicationProfileRESTService/GetMedicationProfile", ReplyAction="http://tempuri.org/IMedicationProfileRESTService/GetMedicationProfileResponse")]
        Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedicationProfile GetMedicationProfile();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMedicationProfileRESTServiceChannel : Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.IMedicationProfileRESTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedicationProfileRESTServiceClient : System.ServiceModel.ClientBase<Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.IMedicationProfileRESTService>, Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.IMedicationProfileRESTService {
        
        public MedicationProfileRESTServiceClient() {
        }
        
        public MedicationProfileRESTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedicationProfileRESTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicationProfileRESTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicationProfileRESTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Demo.HL7MessageParser.ServiceSimulator.Test.MedicationProfileRESTServiceReference.MedicationProfile GetMedicationProfile() {
            return base.Channel.GetMedicationProfile();
        }
    }
}
