//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.HL7MessageParser.DTOs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TAMPA-FS1;Initial Catalog=ADS_NEW;Persist Security Info=True;User ID=" +
            "sa;Password=md1599")]
        public string ADS_NEWConnectionString {
            get {
                return ((string)(this["ADS_NEWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=ADS_MULTI_PASS;Integrated Security=True")]
        public string ADS_MULTI_PASSConnectionString {
            get {
                return ((string)(this["ADS_MULTI_PASSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV-TEST\\SQLEXPRESS;Initial Catalog=ADS_NEW_GEN4X;Persist Security In" +
            "fo=True;User ID=sa;Password=md1599")]
        public string ADS_NEW_GEN4XConnectionString {
            get {
                return ((string)(this["ADS_NEW_GEN4XConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.232.128.148\\SQLEXPRESS;Initial Catalog=ADS_NEW_GEN4X;User ID=sa;Pa" +
            "ssword=md1599")]
        public string ADS_NEW_GEN4XConnectionString1 {
            get {
                return ((string)(this["ADS_NEW_GEN4XConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CONFIG3752;Initial Catalog=ADS_NEW;Persist Security Info=True;User ID" +
            "=sa;Password=md1599")]
        public string ADS_NEWConnectionString1 {
            get {
                return ((string)(this["ADS_NEWConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.232.128.104\\SQLEXPRESS;Initial Catalog=ADS_STARTUP_DB;User ID=sa;P" +
            "assword=md1599")]
        public string ADS_STARTUP_DBConnectionString {
            get {
                return ((string)(this["ADS_STARTUP_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=ADS_EDU_G5;Integrated Security=False; Us" +
            "er ID = sa; Password = Password1")]
        public string metro_testConnectionString {
            get {
                return ((string)(this["metro_testConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CONFIG3752\\MSSQLSERVER2008;Initial Catalog=metro_test;Integrated Secu" +
            "rity=True")]
        public string metro_testConnectionString1 {
            get {
                return ((string)(this["metro_testConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ADS_EDU_G5;Integrated Security=True")]
        public string ADS_EDU_G5ConnectionString {
            get {
                return ((string)(this["ADS_EDU_G5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLExpress;Initial Catalog=ADS_EDU_G5;Integrated Security=True")]
        public string ADS_EDU_G5ConnectionString1 {
            get {
                return ((string)(this["ADS_EDU_G5ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ADS_CART;Integrated Security=True")]
        public string ADS_CARTConnectionString {
            get {
                return ((string)(this["ADS_CARTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=ADS_CART;Integrated Security=True")]
        public string ADS_CARTConnectionString1 {
            get {
                return ((string)(this["ADS_CARTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EDU_G5;Integrated Security=True")]
        public string EDU_G5ConnectionString {
            get {
                return ((string)(this["EDU_G5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=ADS_CART;Persist Security Info=True;User" +
            " ID=sa;Password=Password1")]
        public string ADS_CARTConnectionString2 {
            get {
                return ((string)(this["ADS_CARTConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ADS_EDU_G5_R1S16;Integrated Security=True")]
        public string ADS_EDU_G5_R1S16ConnectionString {
            get {
                return ((string)(this["ADS_EDU_G5_R1S16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CNXA1ER-L0544\\SQLEXPRESS;Initial Catalog=ADS_EDU_G5R1S16;Persist Secu" +
            "rity Info=True;User ID=sa;Password=Password1")]
        public string ADS_EDU_G5R1S16ConnectionString {
            get {
                return ((string)(this["ADS_EDU_G5R1S16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Initial Catalog=ADS_EDU_G5R1S16;Persist Security" +
            " Info=True;User ID=sa;Password=Password1")]
        public string ADS_EDU_G5R1S16ConnectionString1 {
            get {
                return ((string)(this["ADS_EDU_G5R1S16ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=ADS_STARTUP_DB;Integrated Security=True")]
        public string ADS_STARTUP_DBConnectionString1 {
            get {
                return ((string)(this["ADS_STARTUP_DBConnectionString1"]));
            }
        }
    }
}
