
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
namespace Demo.HL7MessageParser.WebProxy
{
    // 
    // This source code was auto-generated by wsdl, Version=4.6.81.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PreparationServiceSoap", Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class PreparationService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private WorkContextSoapHeader workContextField;

        private System.Threading.SendOrPostCallback getPreparationOperationCompleted;

        private System.Threading.SendOrPostCallback getDrugMdsPropertyHqOperationCompleted;

        /// <remarks/>
        public PreparationService(string url)
        {
            this.Url = url;
        }

        public WorkContextSoapHeader WorkContext
        {
            get
            {
                return this.workContextField;
            }
            set
            {
                this.workContextField = value;
            }
        }

        /// <remarks/>
        public event getPreparationCompletedEventHandler getPreparationCompleted;

        /// <remarks/>
        public event getDrugMdsPropertyHqCompletedEventHandler getDrugMdsPropertyHqCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("WorkContext", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://biz.dms.pms.model.ha.org.hk/getPreparation", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPreparationResponse", Namespace = "http://biz.dms.pms.model.ha.org.hk/", IsNullable = true)]
        public GetPreparationResponse getPreparation([System.Xml.Serialization.XmlElementAttribute("getPreparation", Namespace = "http://biz.dms.pms.model.ha.org.hk/", IsNullable = true)] GetPreparationRequest getPreparation1)
        {
            object[] results = this.Invoke("getPreparation", new object[] {
                    getPreparation1});
            return ((GetPreparationResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetPreparation(GetPreparationRequest getPreparation1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getPreparation", new object[] {
                    getPreparation1}, callback, asyncState);
        }

        /// <remarks/>
        public GetPreparationResponse EndgetPreparation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetPreparationResponse)(results[0]));
        }

        /// <remarks/>
        public void getPreparationAsync(GetPreparationRequest getPreparation1)
        {
            this.getPreparationAsync(getPreparation1, null);
        }

        /// <remarks/>
        public void getPreparationAsync(GetPreparationRequest getPreparation1, object userState)
        {
            if ((this.getPreparationOperationCompleted == null))
            {
                this.getPreparationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPreparationOperationCompleted);
            }
            this.InvokeAsync("getPreparation", new object[] {
                    getPreparation1}, this.getPreparationOperationCompleted, userState);
        }

        private void OngetPreparationOperationCompleted(object arg)
        {
            if ((this.getPreparationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPreparationCompleted(this, new getPreparationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("WorkContext", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://biz.dms.pms.model.ha.org.hk/getDrugMdsPropertyHq", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getDrugMdsPropertyHqResponse", Namespace = "http://biz.dms.pms.model.ha.org.hk/", IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("return", IsNullable = false)]
        public ReturnObj[] getDrugMdsPropertyHq([System.Xml.Serialization.XmlElementAttribute("getDrugMdsPropertyHq", Namespace = "http://biz.dms.pms.model.ha.org.hk/", IsNullable = true)] getDrugMdsPropertyHq getDrugMdsPropertyHq1)
        {
            object[] results = this.Invoke("getDrugMdsPropertyHq", new object[] {
                    getDrugMdsPropertyHq1});
            return ((ReturnObj[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetDrugMdsPropertyHq(getDrugMdsPropertyHq getDrugMdsPropertyHq1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getDrugMdsPropertyHq", new object[] {
                    getDrugMdsPropertyHq1}, callback, asyncState);
        }

        /// <remarks/>
        public ReturnObj[] EndgetDrugMdsPropertyHq(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnObj[])(results[0]));
        }

        /// <remarks/>
        public void getDrugMdsPropertyHqAsync(getDrugMdsPropertyHq getDrugMdsPropertyHq1)
        {
            this.getDrugMdsPropertyHqAsync(getDrugMdsPropertyHq1, null);
        }

        /// <remarks/>
        public void getDrugMdsPropertyHqAsync(getDrugMdsPropertyHq getDrugMdsPropertyHq1, object userState)
        {
            if ((this.getDrugMdsPropertyHqOperationCompleted == null))
            {
                this.getDrugMdsPropertyHqOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDrugMdsPropertyHqOperationCompleted);
            }
            this.InvokeAsync("getDrugMdsPropertyHq", new object[] {
                    getDrugMdsPropertyHq1}, this.getDrugMdsPropertyHqOperationCompleted, userState);
        }

        private void OngetDrugMdsPropertyHqOperationCompleted(object arg)
        {
            if ((this.getDrugMdsPropertyHqCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDrugMdsPropertyHqCompleted(this, new getDrugMdsPropertyHqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class DrugProperty
    {

        private string displaynameField;

        private string dosageCompulField;

        private string drugKeyField;

        private string fixedPeriodField;

        private string formCodeField;

        private string saltPropertyField;

        private string screenDisplaynameField;

        private string screenSaltField;

        private string strengthCompulField;

        private string updateDateField;

        private string updateUserField;

        private string updateVersionField;

        /// <remarks/>
        public string displayname
        {
            get
            {
                return this.displaynameField;
            }
            set
            {
                this.displaynameField = value;
            }
        }

        /// <remarks/>
        public string dosageCompul
        {
            get
            {
                return this.dosageCompulField;
            }
            set
            {
                this.dosageCompulField = value;
            }
        }

        /// <remarks/>
        public string drugKey
        {
            get
            {
                return this.drugKeyField;
            }
            set
            {
                this.drugKeyField = value;
            }
        }

        /// <remarks/>
        public string fixedPeriod
        {
            get
            {
                return this.fixedPeriodField;
            }
            set
            {
                this.fixedPeriodField = value;
            }
        }

        /// <remarks/>
        public string formCode
        {
            get
            {
                return this.formCodeField;
            }
            set
            {
                this.formCodeField = value;
            }
        }

        /// <remarks/>
        public string saltProperty
        {
            get
            {
                return this.saltPropertyField;
            }
            set
            {
                this.saltPropertyField = value;
            }
        }

        /// <remarks/>
        public string screenDisplayname
        {
            get
            {
                return this.screenDisplaynameField;
            }
            set
            {
                this.screenDisplaynameField = value;
            }
        }

        /// <remarks/>
        public string screenSalt
        {
            get
            {
                return this.screenSaltField;
            }
            set
            {
                this.screenSaltField = value;
            }
        }

        /// <remarks/>
        public string strengthCompul
        {
            get
            {
                return this.strengthCompulField;
            }
            set
            {
                this.strengthCompulField = value;
            }
        }

        /// <remarks/>
        public string updateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        public string updateUser
        {
            get
            {
                return this.updateUserField;
            }
            set
            {
                this.updateUserField = value;
            }
        }

        /// <remarks/>
        public string updateVersion
        {
            get
            {
                return this.updateVersionField;
            }
            set
            {
                this.updateVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class DrugMDSObj
    {

        private string duplicateFlagField;

        private string gcnSeqnoField;

        private string groupGcnSeqnoField;

        private string groupMoeCheckFlagField;

        private string groupRoutedGenericField;

        private string groupRouteformGenericField;

        private string groupSingleIngredField;

        private string hiclSeqnoField;

        private string moeCheckFlagField;

        private string routedGenericField;

        private string routeformGenericField;

        /// <remarks/>
        public string duplicateFlag
        {
            get
            {
                return this.duplicateFlagField;
            }
            set
            {
                this.duplicateFlagField = value;
            }
        }

        /// <remarks/>
        public string gcnSeqno
        {
            get
            {
                return this.gcnSeqnoField;
            }
            set
            {
                this.gcnSeqnoField = value;
            }
        }

        /// <remarks/>
        public string groupGcnSeqno
        {
            get
            {
                return this.groupGcnSeqnoField;
            }
            set
            {
                this.groupGcnSeqnoField = value;
            }
        }

        /// <remarks/>
        public string groupMoeCheckFlag
        {
            get
            {
                return this.groupMoeCheckFlagField;
            }
            set
            {
                this.groupMoeCheckFlagField = value;
            }
        }

        /// <remarks/>
        public string groupRoutedGeneric
        {
            get
            {
                return this.groupRoutedGenericField;
            }
            set
            {
                this.groupRoutedGenericField = value;
            }
        }

        /// <remarks/>
        public string groupRouteformGeneric
        {
            get
            {
                return this.groupRouteformGenericField;
            }
            set
            {
                this.groupRouteformGenericField = value;
            }
        }

        /// <remarks/>
        public string groupSingleIngred
        {
            get
            {
                return this.groupSingleIngredField;
            }
            set
            {
                this.groupSingleIngredField = value;
            }
        }

        /// <remarks/>
        public string hiclSeqno
        {
            get
            {
                return this.hiclSeqnoField;
            }
            set
            {
                this.hiclSeqnoField = value;
            }
        }

        /// <remarks/>
        public string moeCheckFlag
        {
            get
            {
                return this.moeCheckFlagField;
            }
            set
            {
                this.moeCheckFlagField = value;
            }
        }

        /// <remarks/>
        public string routedGeneric
        {
            get
            {
                return this.routedGenericField;
            }
            set
            {
                this.routedGenericField = value;
            }
        }

        /// <remarks/>
        public string routeformGeneric
        {
            get
            {
                return this.routeformGenericField;
            }
            set
            {
                this.routeformGenericField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class ReturnObj
    {

        private string drugKeyField;

        private DrugMDSObj drugMdsField;

        private DrugProperty drugPropertyField;

        private string itemCodeField;

        /// <remarks/>
        public string drugKey
        {
            get
            {
                return this.drugKeyField;
            }
            set
            {
                this.drugKeyField = value;
            }
        }

        /// <remarks/>
        public DrugMDSObj drugMds
        {
            get
            {
                return this.drugMdsField;
            }
            set
            {
                this.drugMdsField = value;
            }
        }

        /// <remarks/>
        public DrugProperty drugProperty
        {
            get
            {
                return this.drugPropertyField;
            }
            set
            {
                this.drugPropertyField = value;
            }
        }

        /// <remarks/>
        public string itemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class getDrugMdsPropertyHq
    {

        private string[] arg0Field;

        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("itemCode", IsNullable = false)]
        public string[] arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns
        {
            get
            {
                return this.xmlnsField;
            }
            set
            {
                this.xmlnsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublicDrugPatTypeCharge
    {

        private string addedChargeField;

        private string handleChargeField;

        private string markupFactorField;

        /// <remarks/>
        public string addedCharge
        {
            get
            {
                return this.addedChargeField;
            }
            set
            {
                this.addedChargeField = value;
            }
        }

        /// <remarks/>
        public string handleCharge
        {
            get
            {
                return this.handleChargeField;
            }
            set
            {
                this.handleChargeField = value;
            }
        }

        /// <remarks/>
        public string markupFactor
        {
            get
            {
                return this.markupFactorField;
            }
            set
            {
                this.markupFactorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrivateDrugPatTypeCharge
    {

        private string addedChargeField;

        private string handleChargeField;

        private string markupFactorField;

        /// <remarks/>
        public string addedCharge
        {
            get
            {
                return this.addedChargeField;
            }
            set
            {
                this.addedChargeField = value;
            }
        }

        /// <remarks/>
        public string handleCharge
        {
            get
            {
                return this.handleChargeField;
            }
            set
            {
                this.handleChargeField = value;
            }
        }

        /// <remarks/>
        public string markupFactor
        {
            get
            {
                return this.markupFactorField;
            }
            set
            {
                this.markupFactorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DrugMds
    {

        private string duplicateFlagField;

        private string gcnSeqnoField;

        private string groupGcnSeqnoField;

        private string groupMoeCheckFlagField;

        private string groupRoutedGenericField;

        private string groupRouteformGenericField;

        private string groupSingleIngredField;

        private string hiclSeqnoField;

        private string moeCheckFlagField;

        private string routedGenericField;

        private string routeformGenericField;

        /// <remarks/>
        public string duplicateFlag
        {
            get
            {
                return this.duplicateFlagField;
            }
            set
            {
                this.duplicateFlagField = value;
            }
        }

        /// <remarks/>
        public string gcnSeqno
        {
            get
            {
                return this.gcnSeqnoField;
            }
            set
            {
                this.gcnSeqnoField = value;
            }
        }

        /// <remarks/>
        public string groupGcnSeqno
        {
            get
            {
                return this.groupGcnSeqnoField;
            }
            set
            {
                this.groupGcnSeqnoField = value;
            }
        }

        /// <remarks/>
        public string groupMoeCheckFlag
        {
            get
            {
                return this.groupMoeCheckFlagField;
            }
            set
            {
                this.groupMoeCheckFlagField = value;
            }
        }

        /// <remarks/>
        public string groupRoutedGeneric
        {
            get
            {
                return this.groupRoutedGenericField;
            }
            set
            {
                this.groupRoutedGenericField = value;
            }
        }

        /// <remarks/>
        public string groupRouteformGeneric
        {
            get
            {
                return this.groupRouteformGenericField;
            }
            set
            {
                this.groupRouteformGenericField = value;
            }
        }

        /// <remarks/>
        public string groupSingleIngred
        {
            get
            {
                return this.groupSingleIngredField;
            }
            set
            {
                this.groupSingleIngredField = value;
            }
        }

        /// <remarks/>
        public string hiclSeqno
        {
            get
            {
                return this.hiclSeqnoField;
            }
            set
            {
                this.hiclSeqnoField = value;
            }
        }

        /// <remarks/>
        public string moeCheckFlag
        {
            get
            {
                return this.moeCheckFlagField;
            }
            set
            {
                this.moeCheckFlagField = value;
            }
        }

        /// <remarks/>
        public string routedGeneric
        {
            get
            {
                return this.routedGenericField;
            }
            set
            {
                this.routedGenericField = value;
            }
        }

        /// <remarks/>
        public string routeformGeneric
        {
            get
            {
                return this.routeformGenericField;
            }
            set
            {
                this.routeformGenericField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Return
    {

        private string averageUnitPriceField;

        private string baseUnitField;

        private string corpDrugPriceField;

        private string dangerousDrugField;

        private DrugMds drugMdsField;

        private string formCodeField;

        private string formRankField;

        private string fullRouteDescField;

        private string groupBaseUnitField;

        private string isCommonDoseField;

        private string itemCodeField;

        private string moeDescField;

        private string moeRouteFormDescField;

        private string pmsFmStatusField;

        private string ppmiField;

        private string preparationDescField;

        private PrivateDrugPatTypeCharge privateDrugPatTypeChargeField;

        private string publicCdpField;

        private PublicDrugPatTypeCharge publicDrugPatTypeChargeField;

        private string routeDescField;

        private string routeFormSortSeqField;

        private string routeSortSeqField;

        private string saltPropertyField;

        private string sfiCategoryField;

        private string specRestrictField;

        private string strengthField;

        private string strengthUnitField;

        private string strengthValueField;

        private string trueDisplaynameField;

        private string volumeUnitField;

        private string volumeValueField;

        /// <remarks/>
        public string averageUnitPrice
        {
            get
            {
                return this.averageUnitPriceField;
            }
            set
            {
                this.averageUnitPriceField = value;
            }
        }

        /// <remarks/>
        public string baseUnit
        {
            get
            {
                return this.baseUnitField;
            }
            set
            {
                this.baseUnitField = value;
            }
        }

        /// <remarks/>
        public string corpDrugPrice
        {
            get
            {
                return this.corpDrugPriceField;
            }
            set
            {
                this.corpDrugPriceField = value;
            }
        }

        /// <remarks/>
        public string dangerousDrug
        {
            get
            {
                return this.dangerousDrugField;
            }
            set
            {
                this.dangerousDrugField = value;
            }
        }

        /// <remarks/>
        public DrugMds drugMds
        {
            get
            {
                return this.drugMdsField;
            }
            set
            {
                this.drugMdsField = value;
            }
        }

        /// <remarks/>
        public string formCode
        {
            get
            {
                return this.formCodeField;
            }
            set
            {
                this.formCodeField = value;
            }
        }

        /// <remarks/>
        public string formRank
        {
            get
            {
                return this.formRankField;
            }
            set
            {
                this.formRankField = value;
            }
        }

        /// <remarks/>
        public string fullRouteDesc
        {
            get
            {
                return this.fullRouteDescField;
            }
            set
            {
                this.fullRouteDescField = value;
            }
        }

        /// <remarks/>
        public string groupBaseUnit
        {
            get
            {
                return this.groupBaseUnitField;
            }
            set
            {
                this.groupBaseUnitField = value;
            }
        }

        /// <remarks/>
        public string isCommonDose
        {
            get
            {
                return this.isCommonDoseField;
            }
            set
            {
                this.isCommonDoseField = value;
            }
        }

        /// <remarks/>
        public string itemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }

        /// <remarks/>
        public string moeDesc
        {
            get
            {
                return this.moeDescField;
            }
            set
            {
                this.moeDescField = value;
            }
        }

        /// <remarks/>
        public string moeRouteFormDesc
        {
            get
            {
                return this.moeRouteFormDescField;
            }
            set
            {
                this.moeRouteFormDescField = value;
            }
        }

        /// <remarks/>
        public string pmsFmStatus
        {
            get
            {
                return this.pmsFmStatusField;
            }
            set
            {
                this.pmsFmStatusField = value;
            }
        }

        /// <remarks/>
        public string ppmi
        {
            get
            {
                return this.ppmiField;
            }
            set
            {
                this.ppmiField = value;
            }
        }

        /// <remarks/>
        public string preparationDesc
        {
            get
            {
                return this.preparationDescField;
            }
            set
            {
                this.preparationDescField = value;
            }
        }

        /// <remarks/>
        public PrivateDrugPatTypeCharge privateDrugPatTypeCharge
        {
            get
            {
                return this.privateDrugPatTypeChargeField;
            }
            set
            {
                this.privateDrugPatTypeChargeField = value;
            }
        }

        /// <remarks/>
        public string publicCdp
        {
            get
            {
                return this.publicCdpField;
            }
            set
            {
                this.publicCdpField = value;
            }
        }

        /// <remarks/>
        public PublicDrugPatTypeCharge publicDrugPatTypeCharge
        {
            get
            {
                return this.publicDrugPatTypeChargeField;
            }
            set
            {
                this.publicDrugPatTypeChargeField = value;
            }
        }

        /// <remarks/>
        public string routeDesc
        {
            get
            {
                return this.routeDescField;
            }
            set
            {
                this.routeDescField = value;
            }
        }

        /// <remarks/>
        public string routeFormSortSeq
        {
            get
            {
                return this.routeFormSortSeqField;
            }
            set
            {
                this.routeFormSortSeqField = value;
            }
        }

        /// <remarks/>
        public string routeSortSeq
        {
            get
            {
                return this.routeSortSeqField;
            }
            set
            {
                this.routeSortSeqField = value;
            }
        }

        /// <remarks/>
        public string saltProperty
        {
            get
            {
                return this.saltPropertyField;
            }
            set
            {
                this.saltPropertyField = value;
            }
        }

        /// <remarks/>
        public string sfiCategory
        {
            get
            {
                return this.sfiCategoryField;
            }
            set
            {
                this.sfiCategoryField = value;
            }
        }

        /// <remarks/>
        public string specRestrict
        {
            get
            {
                return this.specRestrictField;
            }
            set
            {
                this.specRestrictField = value;
            }
        }

        /// <remarks/>
        public string strength
        {
            get
            {
                return this.strengthField;
            }
            set
            {
                this.strengthField = value;
            }
        }

        /// <remarks/>
        public string strengthUnit
        {
            get
            {
                return this.strengthUnitField;
            }
            set
            {
                this.strengthUnitField = value;
            }
        }

        /// <remarks/>
        public string strengthValue
        {
            get
            {
                return this.strengthValueField;
            }
            set
            {
                this.strengthValueField = value;
            }
        }

        /// <remarks/>
        public string trueDisplayname
        {
            get
            {
                return this.trueDisplaynameField;
            }
            set
            {
                this.trueDisplaynameField = value;
            }
        }

        /// <remarks/>
        public string volumeUnit
        {
            get
            {
                return this.volumeUnitField;
            }
            set
            {
                this.volumeUnitField = value;
            }
        }

        /// <remarks/>
        public string volumeValue
        {
            get
            {
                return this.volumeValueField;
            }
            set
            {
                this.volumeValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class GetPreparationResponse
    {

        private Return returnField;

        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "")]
        public Return @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns
        {
            get
            {
                return this.xmlnsField;
            }
            set
            {
                this.xmlnsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Arg0
    {

        private string dispHospCodeField;

        private string dispWorkstoreField;

        private string itemCodeField;

        private string trueDisplaynameField;

        private string formCodeField;

        private string saltPropertyField;

        private string drugScopeField;

        private string specialtyTypeField;

        private string pasSpecialtyField;

        private string pasSubSpecialtyField;

        private string costIncludedField;

        private string hqFlagField;

        /// <remarks/>
        public string dispHospCode
        {
            get
            {
                return this.dispHospCodeField;
            }
            set
            {
                this.dispHospCodeField = value;
            }
        }

        /// <remarks/>
        public string dispWorkstore
        {
            get
            {
                return this.dispWorkstoreField;
            }
            set
            {
                this.dispWorkstoreField = value;
            }
        }

        /// <remarks/>
        public string itemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }

        /// <remarks/>
        public string trueDisplayname
        {
            get
            {
                return this.trueDisplaynameField;
            }
            set
            {
                this.trueDisplaynameField = value;
            }
        }

        /// <remarks/>
        public string formCode
        {
            get
            {
                return this.formCodeField;
            }
            set
            {
                this.formCodeField = value;
            }
        }

        /// <remarks/>
        public string saltProperty
        {
            get
            {
                return this.saltPropertyField;
            }
            set
            {
                this.saltPropertyField = value;
            }
        }

        /// <remarks/>
        public string drugScope
        {
            get
            {
                return this.drugScopeField;
            }
            set
            {
                this.drugScopeField = value;
            }
        }

        /// <remarks/>
        public string specialtyType
        {
            get
            {
                return this.specialtyTypeField;
            }
            set
            {
                this.specialtyTypeField = value;
            }
        }

        /// <remarks/>
        public string pasSpecialty
        {
            get
            {
                return this.pasSpecialtyField;
            }
            set
            {
                this.pasSpecialtyField = value;
            }
        }

        /// <remarks/>
        public string pasSubSpecialty
        {
            get
            {
                return this.pasSubSpecialtyField;
            }
            set
            {
                this.pasSubSpecialtyField = value;
            }
        }

        /// <remarks/>
        public string costIncluded
        {
            get
            {
                return this.costIncludedField;
            }
            set
            {
                this.costIncludedField = value;
            }
        }

        /// <remarks/>
        public string hqFlag
        {
            get
            {
                return this.hqFlagField;
            }
            set
            {
                this.hqFlagField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://biz.dms.pms.model.ha.org.hk/")]
    public partial class GetPreparationRequest
    {

        private Arg0 arg0Field;

        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "")]
        public Arg0 arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns
        {
            get
            {
                return this.xmlnsField;
            }
            set
            {
                this.xmlnsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void getPreparationCompletedEventHandler(object sender, getPreparationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPreparationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getPreparationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetPreparationResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetPreparationResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void getDrugMdsPropertyHqCompletedEventHandler(object sender, getDrugMdsPropertyHqCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDrugMdsPropertyHqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getDrugMdsPropertyHqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ReturnObj[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ReturnObj[])(this.results[0]));
            }
        }
    }
}